"""password

Revision ID: 48b5af7979e8
Revises: 04d8ff53da5b
Create Date: 2021-06-14 10:36:55.053737

"""
from alembic import op
import sqlalchemy as sa

from config import settings
from library.auth.hash import get_password_hash


# revision identifiers, used by Alembic.
revision = '48b5af7979e8'
down_revision = '04d8ff53da5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=256)))
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)

    # ### end Alembic commands ###

    op.execute('update users set password_hash = login')  # temp, just to populate
    app_settings = settings
    admin_password = get_password_hash(app_settings.PASSWORD_SALT, 'admin_password')
    op.execute(f'update users set password_hash = \'{admin_password}\' where login = \'admin\'')  # temp, just to populate
    op.alter_column('users', 'password_hash',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
